### ISSUE TITLE
Datawedge & Ionic2

### ISSUE THREAD

**Issue by willemjanvankranenburg** [darryncampbell/DataWedge-Cordova-Sample#2]
Hello,

I want to create an IONIC2 app for a Zebra TC8000 scanner. I tried using your plugin but without any luck. 

I used [the developer.zebra.com tutorial for cordova](https://developer.zebra.com/community/android/android-forums/android-blogs/blog/2016/08/04/integrating-datawedge-into-your-cordova-application). I followed this tutorial step by step, but instead of window.plugins.intentShim.registerBroadcastReceiver I used
the following code in the constructor (in **typescript**):

`window['plugins'].intentShim.registerBroadcastReceiver(() => {`
`     let filterActions: ['com.zebra.datawedgecordova.ACTION'],`
`     filterCategories: ['com.android.intent.category.DEFAULT']`
`}, (intent) => {`
`     this.broadcastReceived = "Broadcast Received = true"`
`     //  Broadcast received  `
`     console.log('Received Intent: ' + JSON.stringify(intent.extras));`
`     if (intent.extras["com.symbol.datawedge.data_string"] != null) {`
`         this.broadcastBarcode = intent.extras["com.symbol.datawedge.data_string"];`
`     }`
`});`

in my HTML file, i have a `<p> {{broadcastReceived}} , {{broadcastBarcode}} </p>`.

When I run this on my Zebra scanner the console.log never "fires" and this.broadcastBarcode isn't set, so the code never comes in the `if`

Do you know if it's possible? And how? Is there something i have to import? (installed the darryncampbell-cordova-plugin-intent)

Willem-Jan

**Comment by darryncampbell** [comment]
Some people report a problem with the intent plugin and ionic. Did you see https://github.com/ionic-team/ionic-native/issues/1609 ?

**Comment by as2081** [comment]
Hi,

I am trying to integrate your plugin with my ionic2/angular2 app and am also using the code above. I have looked through all of the current issues and the link posted above but none of them seem to replicate my problem.
![capture 1](https://user-images.githubusercontent.com/22677127/33825922-1d39a31a-de5b-11e7-820a-75f6b9dcc4d3.PNG)
![capture](https://user-images.githubusercontent.com/22677127/33825923-1d52ab9e-de5b-11e7-9abe-b4e73243a004.PNG)

I have tried changing my code to _Window['intentShim'].registerBroadcastReceiver_ but the error is the same just stating that _registerBroadcastReceiver_ is undefined.

Could you please let me know if I must import the intent plugin into the typescript page and how to do so as I have not found a way to do this.

Thanks in advance

**Comment by darryncampbell** [comment]
Hi, for Ionic2/Angular2 you could try WebIntent, https://ionicframework.com/docs/native/web-intent/.  The underlying implementation is the same plugin as intentShim.  Please see that page for examples, though I haven't had the opportunity to try it myself.

**Comment by willemjanvankranenburg** [comment]
I fixed it using the WebIntent plugin (as said by darryncampbell in the post above) and the following bit of code:

```
this.platform.ready().then(() => {
    (<any>window).plugins.intentShim.registerBroadcastReceiver({
        filterActions: ['com.zebra.datawedgecordova.ACTION'],
        filterCategories: ['com.android.intent.category.DEFAULT']
    }, (intent) => {
        console.log("registerBroadcast: " + JSON.stringify(intent.extras["com.symbol.datawedge.data_string"]));
    });
}).catch((error) => {
    console.log("catch: " + error);
});
```

The main thing to notice is **(< any >window).plugins.intentShim** instead of **window['plugins'].intentShim**

**Comment by as2081** [comment]
Ah thank you @willemjanvankranenburg! 

Can I just ask what the _this.platform.ready().then(()_ is doing, just initialising? And what do you have in your constructor so that it works? I do not have anything related to _this.platform_.

**Comment by willemjanvankranenburg** [comment]
@as2081 platform is a ionic-angular component it's there just to make sure IONIC is ready and the modules are fully loaded (I think at least); I have the following:

```
import { Platform } from 'ionic-angular';
...
...
...
constructor(private platform: Platform) {
    .... here comes the code to register your broadcast ...
}
```

**Comment by as2081** [comment]
Ah yes thank you. I have all of that and it is now compiling fine but it catches the error _TypeError: Cannot read property 'intentShim' of undefined_ and am not sure why I am still not finding the _intentShim_?

Sorry about all the questions, I have been stuck on this problem for a long time now so thank you for your help!

**Comment by nosTa1337** [comment]
I would also been interested in @willemjanvankranenburg 's solution. Can you post your whole code? Where do you use the webintent here? Got the same error as @as2081 

Ok i got it working and I think we don't need the webintent for it.

I used @willemjanvankranenburg solution and just added intentShim: any as a variable.

**Comment by as2081** [comment]
I still get the same error, even with the _var intentShim: any_
![image](https://user-images.githubusercontent.com/22677127/33988096-20ee809a-e0bb-11e7-9b1d-60e383fa81b8.png)

**Comment by nosTa1337** [comment]
make sure u don't use it in the browser and only on the device / or npm run browser. Most plugins will only work on the device. Mine is working fine now

**Comment by darryncampbell** [comment]
In case anybody comes across this thread and needs an example implementation, I threw something simple together this morning that receives a DataWedge barcode with Ionic2: https://github.com/darryncampbell/DataWedgeIonic2

**Comment by as2081** [comment]
Thank you but I still cannot recognise _intentShim_, even on your DataWedgeIonic2 app. It seems as if it does not recognise _plugins_ as a property of _<any>window_ as I am still getting the same error as I was before.

**Comment by willemjanvankranenburg** [comment]
@as2081 are you running your app in the browser, or as a "real" app on a device? On a device it should work, it doesn't work in the browser.

**Comment by as2081** [comment]
@willemjanvankranenburg I am doing both but there is no way to debug on my device. Surely if it is not entering the function on the browser it will not enter it on the device either?

**Comment by willemjanvankranenburg** [comment]
if you have Chrome, you can debug your device with the chrome developer tools (Chrome Dev Tools -> Options (3 dots right of the console) -> remote devices)

**Comment by nosTa1337** [comment]
did you configure your datawedge correctly? You can try "debug" it with chrome://inspect and put some console outputs inside or run it with --debug option to be able to debug with chrome

**Comment by as2081** [comment]
Yes but chrome is my browser, it is not being used on my zebra device?

And I'm not sure if I have my datawedge configured correctly, how did you do yours? @nosTa1337 

Where do you guys have the intent plugin stored and how is it linked with the typescript file you are using? @willemjanvankranenburg

**Comment by nosTa1337** [comment]
It doesn't matter if you are using chrome on your device. You have to connect your zebra device to your computer via usb and have usb debugging enabled.

As soon as you start your app you should see a similar picture:


![2017-12-14 16_10_03-inspect with chrome developer tools](https://user-images.githubusercontent.com/13113717/33999044-a5ec7850-e0e9-11e7-8280-f210aba56b29.png)

This is my datawedge configuration.
![screenshot-1513255483222](https://user-images.githubusercontent.com/13113717/33999067-b8684eb4-e0e9-11e7-8d4c-c8b9750374c7.jpg)

![screenshot-1513255497405](https://user-images.githubusercontent.com/13113717/33999068-b8a01ab0-e0e9-11e7-8141-9e7dbba12060.jpg)

And this is my app configuration:

`if (this.platform.is('cordova') && this.settings.isDataWedge)
    {
      (<any>window).plugins.intentShim.registerBroadcastReceiver({
        filterActions: ['de.all4cloud.scan4cloud.ACTION'],
        filterCategories: ['com.android.intent.category.DEFAULT']
      }, (intent) =>
        {
          this.barcode$.next(intent.extras["com.symbol.datawedge.data_string"]);
        });
    }`

**Comment by as2081** [comment]
Mine is configured like that, apart from I am still using the same name _'com.zebra.datawedgecordova.ACTION'_ as my intent action. My profile name is still DataWedgeCordova.

Thanks for the help by the way, I really don't know where I have gone wrong yet. @nosTa1337 @willemjanvankranenburg

**Comment by nosTa1337** [comment]
if you like I can take a look via teamviewer. just gimme your email than i will contact you.

**Comment by as2081** [comment]
Thank you but I'm afraid I won't be able to as I am at work and the network will not allow it. @nosTa1337 

Not to worry, it has started working for me now. I think there was a mix up in the configuration. Thank you for your help! @nosTa1337 @willemjanvankranenburg

**Comment by darryncampbell** [comment]
Thank you @nosTa1337 and @willemjanvankranenburg for helping.  If you reach out to me I'll send you some swag but I don't work for corporate so it would not be very exciting!!  Contact details are here: http://www.darryncampbell.co.uk/about/
